site_name: "اندیشکده عقل و انگیزش"
site_description: "Institute of Cognition & Motive"
site_author: "اندیشکده عقل و انگیزش"
site_url: "https://aqloangizeh.ir"

use_directory_urls: true

theme:
  name: material
  language: fa
  direction: rtl
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Conferences:
      - First Conference: https://aqloangizeh.ir/The-Frist-Conference/
  - About: about.md
